# -*- coding: utf-8 -*-
"""
Taules annexes de l'IOF (Estructura-dades-cartografiques-IOF.pdf)
"""

# Taula annexa 1: Formacions forestals (codi → descripció)
# Usada pel camp "for_forestal" de IOF_Rodals / IOF_Unitats_Actuacio
FORMACIONS = [
    ("Aa", "Avetoses"),
    ("Aa_Al", "Altres boscos mixtos dominats per l'avet"),
    ("Aa_Fs", "Boscos mixtos d'avet i faig"),
    ("Aa_Pl", "Boscos mixtos d'avet i altres caducifolis de muntanya"),
    ("Aa_Ps", "Boscos mixtos d'avet i pi roig"),
    ("Aa_Pu", "Boscos mixtos d'avet i pi negre"),
    ("Acc", "Formacions dominades per auró blanc (Acer campestre)"),
    ("Acm", "Formacions dominades per auró negre (Acer monspessulanum)"),
    ("Aco", "Formacions dominades per blada (Acer opalus/granatense)"),
    ("Acp", "Formacions dominades per erable (Acer platanoides)"),
    ("Acs", "Formacions dominades per plàtan fals (Acer pseudoplatanus)"),
    ("Au", "Formacions dominades per arboç (Arbutus unedo)"),
    ("Bpe", "Bedollars"),
    ("Bpe_Aa", "Boscos mixtos de bedoll i avet"),
    ("Bpe_Al", "Altres boscos mixtos dominats pel bedoll"),
    ("Bpe_Pl", "Boscos mixtos de bedoll i altres caducifolis"),
    ("Bpe_Ps", "Boscos mixtos de bedoll i pi roig"),
    ("Bpe_Pu", "Boscos mixtos de bedoll i pi negre"),
    ("Bpu", "Formacions dominades per bedoll pubescent (Betula pubescens)"),
    ("Ce", "Plantacions de cedre"),
    ("Ce_Al", "Plantacions de cedre amb altres espècies"),
    ("Coa", "Avellanedes"),
    ("Coa_Con", "Formacions mixtes d'avellaner i coníferes"),
    ("Coa_Pl", "Formacions mixtes d'avellaner i altres planifolis"),
    ("Cs", "Castanyedes"),
    ("Cs_Al", "Altres boscos mixtos dominats pel castanyer"),
    ("Cs_Co", "Boscos mixtos de castanyer i coníferes"),
    ("Cs_Fs_Qpe", "Boscos mixtos de castanyer amb faig o roure de fulla gran"),
    ("Cs_Pl", "Boscos mixtos de castanyer i altres planifolis"),
    ("Cs_Qs", "Boscos mixtos de castanyer i surera"),
    ("Cs_Qu", "Boscos mixtos de castanyer amb alzines o roures martinenc i africà"),
    ("Eu", "Plantacions d'eucaliptus"),
    ("Eu_Al", "Plantacions d'eucaliptus amb altres espècies"),
    ("Fe", "Freixenedes de freixe de fulla gran"),
    ("Fe_Al", "Altres boscos mixtos dominats pel freixe de fulla gran"),
    ("Fe_Pl", "Boscos mixtos de freixe de fulla gran i altres planifolis"),
    ("Fe_Ps", "Boscos mixtos de freixe de fulla gran i pi roig"),
    ("Fs", "Fagedes"),
    ("Fs_Aa", "Boscos mixtos de faig i avet"),
    ("Fs_Al", "Altres boscos mixtos dominats pel faig"),
    ("Fs_Pl", "Boscos mixtos de faig i altres planifolis"),
    ("Fs_Ps", "Boscos mixtos de faig i pi roig"),
    ("Fs_Pu", "Boscos mixtos de faig i pi negre"),
    ("Fs_Qpe", "Boscos mixtos de faig i roure de fulla gran i pènol"),
    ("Ia", "Formacions dominades per grèvol (Ilex aquifolium)"),
    ("Ju", "Plantacions de noguera"),
    ("Ju_Al", "Plantacions de noguera amb altres espècies"),
    ("La", "Plantacions de làrix"),
    ("La_Al", "Plantacions de làrix amb altres espècies"),
    ("PhCON", "Pinedes de pi blanc continentals"),
    ("PhCON_Qib", "Formacions mixtes de pi blanc continental i carrasca"),
    ("PhLIT", "Pinedes de pi blanc d'influència litoral"),
    ("PhLIT_Qib", "Formacions mixtes de pi blanc litoral i carrasca"),
    ("PhLIT_Qu", "Formacions mixtes de pi blanc litoral i roures"),
    ("Ph_Al", "Altres formacions mixtes dominades pel pi blanc"),
    ("Ph_Bm", "Formacions mixtes de pi blanc i altres pins i frondoses"),
    ("Ph_Pn", "Boscos mixtos de pi blanc i pinassa"),
    ("Ph_Ppa", "Pinedes mixtes de pi blanc i pi pinyer"),
    ("Ph_Ps", "Pinedes mixtes de pi blanc i pi roig"),
    ("Ph_Qii", "Formacions mixtes de pi blanc i alzina"),
    ("Ph_Qs", "Formacions mixtes de pi blanc i surera"),
    ("Pia", "Plantacions de pícea"),
    ("Pia_Al", "Plantacions de pícea amb altres espècies"),
    ("Plh", "Plantacions de plàtan"),
    ("Plh_Al", "Plantacions de plàtan amb altres espècies"),
    ("PnMER", "Boscos de pinassa de l'àmbit meridional"),
    ("PnMER_Ph", "Boscos mixtos de pinassa i pi blanc meridional"),
    ("PnMER_Ps", "Boscos mixtos de pinassa i pi roig meridional"),
    ("PnMER_Qib", "Boscos mixtos de pinassa i carrasca meridional"),
    ("PnMER_Qu", "Boscos mixtos de pinassa i roures meridional"),
    ("PnPRE", "Boscos de pinassa de l'àmbit prepirinenc i central"),
    ("PnPRE_Ph", "Boscos mixtos de pinassa i pi blanc prepirinenc"),
    ("PnPRE_Ps", "Boscos mixtos de pinassa i pi roig prepirinenc"),
    ("PnPRE_Qib", "Boscos mixtos de pinassa i carrasca prepirinenc"),
    ("PnPRE_Qu", "Boscos mixtos de pinassa i roures prepirinenc"),
    ("Pn_Al", "Altres boscos mixtos dominats per la pinassa"),
    ("Pn_Bmm", "Boscos mixtos submediterranis de pinassa, pi blanc i frondoses"),
    ("Pn_Bms", "Boscos mixtos submediterranis de pinassa, pi roig i frondoses"),
    ("Pna", "Plantacions de pinassa d'Àustria"),
    ("Pna_Al", "Plantacions de pinassa d'Àustria amb altres espècies"),
    ("Pnc", "Plantacions de pinassa de Còrsega o Calàbria"),
    ("Pnc_Al", "Plantacions de pinassa de Còrsega o Calàbria amb altres espècies"),
    ("Po", "Plantacions de pollancre"),
    ("Po_Al", "Plantacions de pollancre amb altres espècies"),
    ("Ppa", "Pinedes de pi pinyer"),
    ("Ppa_Al", "Altres formacions mixtes dominades pel pi pinyer"),
    ("Ppa_Bmm", "Formacions mixtes de pi pinyer i altres pins i frondoses"),
    ("Ppa_Ph", "Pinedes mixtes de pi pinyer i pi blanc"),
    ("Ppa_Ppr", "Pinedes mixtes de pi pinyer i pinastre"),
    ("Ppa_Qii", "Formacions mixtes de pi pinyer i alzina"),
    ("Ppa_Qs", "Formacions mixtes de pi pinyer i surera"),
    ("Ppa_Qu", "Formacions mixtes de pi pinyer i roures"),
    ("Ppr", "Plantacions de pinastre"),
    ("Ppr_Al", "Plantacions de pinastre amb altres espècies"),
    ("Ppre", "Boscos de pinastre (poblacions espontànies)"),
    ("Ppre_Al", "Altres boscos mixtos dominats per pinastre espontani"),
    ("Pr", "Plantacions de pi insigne"),
    ("Pr_Al", "Plantacions de pi insigne amb altres espècies"),
    ("Pra", "Plantacions de cirerer"),
    ("Pra_Al", "Plantacions de cirerer amb altres espècies"),
    ("PsMER", "Boscos de pi roig de l'àmbit meridional"),
    ("PsMER_Pn", "Boscos mixtos de pi roig i pinassa meridional"),
    ("PsPIR", "Boscos de pi roig de l'àmbit pirinenc i central"),
    ("PsPIR_Pn", "Boscos mixtos de pi roig i pinassa pirinenc"),
    ("Ps_Aa", "Boscos mixtos de pi roig i avet"),
    ("Ps_Ac", "Boscos mixtos de pi roig i auró o blada"),
    ("Ps_Al", "Altres boscos mixtos dominats pel pi roig"),
    ("Ps_Bms", "Boscos mixtos submediterranis de pi roig i pins i frondoses"),
    ("Ps_Bpe", "Boscos mixtos de pi roig i bedoll"),
    ("Ps_Cm", "Boscos mixtos de pi roig i caducifolis de muntanya"),
    ("Ps_Coa", "Boscos mixtos de pi roig i avellaner"),
    ("Ps_Fs", "Boscos mixtos de pi roig i faig"),
    ("Ps_Pm", "Boscos mixtos de pi roig i pins mediterranis"),
    ("Ps_Pu", "Boscos mixtos de pi roig i pi negre"),
    ("Ps_Qf", "Boscos mixtos de pi roig i roure de fulla petita"),
    ("Ps_Qh", "Boscos mixtos de pi roig i roure martinenc"),
    ("Ps_Qib", "Boscos mixtos de pi roig i carrasca"),
    ("Ps_Qii", "Boscos mixtos de pi roig i alzina"),
    ("Ps_Qpe", "Boscos mixtos de pi roig i roure de fulla gran"),
    ("Ps_Qpy", "Boscos mixtos de pi roig i roure reboll"),
    ("Pt", "Formacions dominades per trèmol (Populus tremula)"),
    ("Ptm", "Plantacions d'avet de Douglas"),
    ("Ptm_Al", "Plantacions d'avet de Douglas amb altres espècies"),
    ("Pu", "Boscos de pi negre"),
    ("Pu_Aa", "Boscos mixtos de pi negre i avet"),
    ("Pu_Al", "Altres boscos mixtos dominats pel pi negre"),
    ("Pu_Bpe", "Boscos mixtos de pi negre i bedolls"),
    ("Pu_Cm", "Boscos mixtos de pi negre i caducifolis de muntanya"),
    ("Pu_Ps", "Boscos mixtos de pi negre i pi roig"),
    ("Qca", "Rouredes de roure africà"),
    ("Qca_Al", "Boscos mixtos dominats pel roure africà"),
    ("Qf", "Rouredes de roure de fulla petita"),
    ("Qf_Al", "Altres boscos mixtos dominats pel roure de fulla petita"),
    ("Qf_Ph", "Boscos mixtos de roure de fulla petita i pi blanc"),
    ("Qf_Pn", "Boscos mixtos de roure de fulla petita i pinassa"),
    ("Qf_Ppa", "Boscos mixtos de roure de fulla petita i pi pinyer"),
    ("Qf_Ps", "Boscos mixtos de roure de fulla petita i pi roig"),
    ("Qf_Qib", "Boscos mixtos de roure de fulla petita i carrasca"),
    ("Qh", "Rouredes de roure martinenc"),
    ("Qh_Al", "Altres boscos mixtos dominats pel roure martinenc"),
    ("Qh_Pl", "Boscos mixtos de roure martinenc i altres planifolis"),
    ("Qh_Pm", "Boscos mixtos de roure martinenc i pins mediterranis"),
    ("Qh_Pn", "Boscos mixtos de roure martinenc i pinassa"),
    ("Qh_Ps", "Boscos mixtos de roure martinenc i pi roig"),
    ("Qh_Qib", "Boscos mixtos de roure martinenc i carrasca"),
    ("Qh_Qii", "Boscos mixtos de roure martinenc i alzina"),
    ("Qh_Qs", "Boscos mixtos de roure martinenc i surera"),
    ("QibMUN", "Carrascars muntanyencs"),
    ("QibMUN_Pn", "Carrascar muntanyenc i pinassa"),
    ("QibMUN_Qu", "Carrascar muntanyenc i roures"),
    ("QibTB", "Carrascars típics o de terra baixa"),
    ("QibTB_Ph", "Boscos mixtos de carrasca i pi blanc"),
    ("QibTB_Pn", "Carrascar de terra baixa i pinassa"),
    ("QibTB_Qu", "Carrascar de terra baixa i roures"),
    ("Qib_Al", "Altres boscos mixtos dominats per la carrasca"),
    ("Qib_Ps", "Boscos mixtos de carrasca i pi roig"),
    ("QiiLIT", "Alzinar litoral"),
    ("QiiLIT_Pl", "Alzinar litoral i altres planifolis"),
    ("QiiLIT_Qu", "Alzinar litoral i roures"),
    ("QiiMUN", "Alzinar muntanyenc"),
    ("QiiMUN_Pl", "Alzinar muntanyenc i altres planifolis"),
    ("QiiMUN_Qu", "Alzinar muntanyenc i roures"),
    ("Qii_Al", "Altres boscos mixtos dominats per l'alzina"),
    ("Qii_Au", "Boscos mixtos d'alzina i arboç"),
    ("Qii_Ph", "Boscos mixtos d'alzina i pi blanc"),
    ("Qii_Pn", "Boscos mixtos d'alzina i pinassa"),
    ("Qii_Ppa", "Boscos mixtos d'alzina i pi pinyer"),
    ("Qii_Ppr", "Boscos mixtos d'alzina i pinastre"),
    ("Qii_Pr", "Formacions mixtes d'alzina i pi insigne"),
    ("Qii_Ps", "Boscos mixtos d'alzina i pi roig"),
    ("Qii_Qs", "Boscos mixtos d'alzina i surera"),
    ("Qpe", "Rouredes de roure de fulla gran"),
    ("Qpe_Al", "Altres boscos mixtos dominats pel roure de fulla gran"),
    ("Qpe_Fs", "Boscos mixtos de roure de fulla gran i faig"),
    ("Qpe_Pl", "Boscos mixtos de roure de fulla gran i altres planifolis"),
    ("Qpe_Ps", "Boscos mixtos de roure de fulla gran i pi roig"),
    ("Qpe_Qii", "Boscos mixtos de roure de fulla gran i alzina"),
    ("Qpy", "Rouredes de roure reboll"),
    ("Qpy_Al", "Altres boscos mixtos dominats pel roure reboll"),
    ("Qpy_Ps", "Boscos mixtos de roure reboll i pi roig"),
    ("Qr", "Rouredes de roure pènol"),
    ("Qr_Pl", "Boscos mixtos de roure pènol i altres planifolis"),
    ("Qs", "Suredes"),
    ("Qs_Al", "Altres boscos mixtos dominats per la surera"),
    ("Qs_Au", "Boscos mixtos de surera i arboç"),
    ("Qs_Ph", "Boscos mixtos de surera i pi blanc"),
    ("Qs_Pl", "Boscos mixtos de surera i altres planifolis"),
    ("Qs_Ppa", "Boscos mixtos de surera i pi pinyer"),
    ("Qs_Ppr", "Boscos mixtos de surera i pinastre"),
    ("Qs_Qii", "Boscos mixtos de surera i alzines"),
    ("Qs_Qu", "Boscos mixtos de surera i roures"),
    ("RIB_MUN_NO", "Formacions de ribera de la muntanya nord-oriental"),
    ("RIB_PIR", "Formacions de ribera de la muntanya pirinenca"),
    ("RIB_PRE", "Formacions de ribera de la muntanya prepirinenca"),
    ("RIB_TB", "Formacions de ribera de terra baixa i muntanya mediterrània"),
    ("RIB_TB_NOR", "Formacions de ribera dels trams baixos nord-orientals"),
    ("Rp", "Formacions dominades per acàcia (Robinia pseudoacacia)"),
    ("Soa", "Formacions dominades per moixera (Sorbus aria)"),
    ("Sot", "Formacions dominades per moixera de pastor (Sorbus torminalis)"),
    ("Sou", "Formacions dominades per moixera de guilla (Sorbus aucuparia)"),
    ("Tb", "Formacions dominades per teix (Taxus baccata)"),
    ("Tic", "Formacions dominades per til·ler de fulla petita (Tilia cordata)"),
    ("Tip", "Formacions dominades per til·ler de fulla gran (Tilia platyphyllos)"),
    ("Ug", "Formacions dominades per oma (Ulmus glabra)"),
    ("c", "Conreu"),
    ("d", "Erm"),
    ("m", "Matollar"),
    ("p", "Pastura"),
    ("r", "Roquissar"),
    ("p_Qru", "Plantacions de roure americà"),
    ("p_Qru_Al", "Plantacions de roure americà amb altres espècies"),
    ("p_Pc", "Plantacions de pi canari"),
    ("p_Pc_Al", "Plantacions de pi canari amb altres espècies"),
    ("p_Fe", "Plantacions de freixe"),
    ("p_Fe_Al", "Plantacions de freixe amb altres espècies"),
    ("p_Fa", "Plantacions de freixe de fulla gran"),
    ("p_Fa_Al", "Plantacions de freixe de fulla gran amb altres espècies"),
    ("p_Acs", "Plantacions de fals plàtan"),
    ("p_Acs_Al", "Plantacions de fals plàtan amb altres espècies"),
    ("p_Acp", "Plantacions d'erable"),
    ("p_Acp_Al", "Plantacions d'erable amb altres espècies"),
    ("p_Acc", "Plantacions d'auró blanc"),
    ("p_Acc_Al", "Plantacions d'auró blanc amb altres espècies"),
    ("p_Sod", "Plantacions de servera"),
    ("p_Sod_Al", "Plantacions de servera amb altres espècies"),
    ("p_Sot", "Plantacions de moixera de pastor"),
    ("p_Sot_Al", "Plantacions de moixera de pastor amb altres espècies"),
    ("p_Pyc", "Plantacions de perera"),
    ("p_Pyc_Al", "Plantacions de perera amb altres espècies"),
    ("p_Mas", "Plantacions de pomera"),
    ("p_Mas_Al", "Plantacions de pomera amb altres espècies"),
    ("p_Tip", "Plantacions de til·ler de fulla gran"),
    ("p_Tip_Al", "Plantacions de til·ler de fulla gran amb altres espècies"),
    ("p_Ji", "Plantacions de noguera híbrida"),
    ("p_Ji_Al", "Plantacions de noguera híbrida amb altres espècies"),
    ("p_Tic", "Plantacions de til·ler de fulla petita"),
]

# Taula annexa 2: Vegetació i usos (codi → nom, forestal S/N, arbrat S/N)
# Font: Estructura-dades-cartografiques-IOF.pdf
USOS_VEGETACIO = [
    ("Aa", "Avet", True, True),
    ("Acc", "Auró blanc", True, True),
    ("Acm", "Auró negre", True, True),
    ("Aco", "Blada", True, True),
    ("Acp", "Erable", True, True),
    ("Acs", "Plàtan fals", True, True),
    ("Alg", "Vern", True, True),
    ("Au", "Arboç", True, True),
    ("Bpe", "Bedoll", True, True),
    ("Bpu", "Bedoll pubescent", True, True),
    ("RIB", "Boscos de ribera", True, True),
    ("Ca", "Lledoner", True, True),
    ("Cs", "Castanyer", True, True),
    ("Ce", "Cedre", True, True),
    ("Coa", "Avellaner", True, True),
    ("Eu", "Eucaliptus", True, True),
    ("Fs", "Faig", True, True),
    ("Fa", "Freixe de fulla petita", True, True),
    ("Fe", "Freixe de fulla gran", True, True),
    ("Ia", "Grèvol", True, True),
    ("Ju", "Noguera", True, True),
    ("La", "Làrix", True, True),
    ("Pia", "Pícea", True, True),
    ("Ph", "Pi blanc", True, True),
    ("Pn", "Pinassa", True, True),
    ("Pna", "Pinassa d'Àustria", True, True),
    ("Pnc", "Pinassa de Còrsega o Calàbria", True, True),
    ("Ppr", "Pinastre", True, True),
    ("Ppa", "Pi pinyer", True, True),
    ("Pr", "Pi insigne", True, True),
    ("Ps", "Pi roig", True, True),
    ("Pu", "Pi negre", True, True),
    ("Plh", "Plàtan", True, True),
    ("Po", "Pollancre", True, True),
    ("Pt", "Trèmol", True, True),
    ("Poa", "Àlber", True, True),
    ("Pon", "Pollancre ver", True, True),
    ("Pra", "Cirerer", True, True),
    ("Ptm", "Avet de Douglas", True, True),
    ("Qca", "Roure africà", True, True),
    ("Qf", "Roure de fulla petita", True, True),
    ("Qh", "Roure martinenc", True, True),
    ("Qib", "Carrasca", True, True),
    ("Qii", "Alzina", True, True),
    ("Qpe", "Roure de fulla gran", True, True),
    ("Qpy", "Roure reboll", True, True),
    ("Qr", "Roure pènol", True, True),
    ("Qs", "Surera", True, True),
    ("Rp", "Acàcia", True, True),
    ("Sa", "Salze", True, True),
    ("Soa", "Moixera", True, True),
    ("Sou", "Moixera de guilla", True, True),
    ("Sot", "Moixera de pastor", True, True),
    ("Tb", "Teix", True, True),
    ("Tic", "Til·ler de fulla petita", True, True),
    ("Tip", "Til·ler de fulla gran", True, True),
    ("Ug", "Oma", True, True),
    ("Um", "Om", True, True),
    ("d", "Erm", True, False),
    ("m", "Matollar", True, False),
    ("p", "Pastura", True, False),
    ("r", "Roquissar", True, False),
    ("c", "Conreu", False, False),
    ("u", "Edificis, equipaments, serveis", False, False),
    ("a", "Aigua", False, False),
    ("v", "Viver", False, False),
]

# Diccionaris derivats per accés ràpid
USOS_DICT = {codi: (nom, forestal, arbrat) for codi, nom, forestal, arbrat in USOS_VEGETACIO}


def is_forestal(codi_us):
    """Retorna True si el codi d'ús és superfície forestal."""
    return USOS_DICT.get(codi_us, (None, False, False))[1]


def is_arbrat(codi_us):
    """Retorna True si el codi d'ús és superfície arbrada."""
    return USOS_DICT.get(codi_us, (None, False, False))[2]


# ---------------------------------------------------------------------------
# Colors MiraMon per a formacions forestals i usos/vegetació
# Font: USVEGET.dbf i TIPFOR.dbf de les paletes MiraMon
# Clau: codi IOF (camp for_forestal o codi_us)
# Valor: (R, G, B)
# ---------------------------------------------------------------------------
COLORS_VEGETACIO = {
    'Aa': (211, 234, 185), 'Acc': (253, 215, 157), 'Acm': (255, 128, 64),
    'Aco': (249, 187, 120), 'Acp': (255, 168, 125), 'Acs': (250, 177, 69),
    'Alg': (255, 200, 100), 'Au': (187, 147, 91), 'Bpe': (255, 241, 109),
    'Bpu': (211, 255, 109), 'Ca': (255, 180, 100), 'Ce': (77, 173, 125),
    'Coa': (230, 220, 100), 'Cs': (189, 97, 239), 'Eu': (168, 134, 168),
    'Fa': (255, 191, 100), 'Fe': (255, 191, 0), 'Fs': (255, 176, 255),
    'Ia': (172, 115, 51), 'Ji': (230, 170, 50), 'Ju': (230, 112, 40),
    'La': (156, 185, 156), 'Mas': (240, 100, 140), 'Pc': (180, 230, 70),
    'Ph': (96, 210, 156), 'Pia': (168, 168, 120), 'Plh': (255, 255, 150),
    'Pn': (77, 145, 77), 'Pna': (77, 145, 77), 'Pnc': (77, 145, 77),
    'Po': (250, 230, 164), 'Poa': (250, 230, 164), 'Pon': (250, 230, 164),
    'Ppa': (108, 255, 108), 'Ppr': (161, 167, 92), 'Pr': (171, 219, 128),
    'Pra': (221, 145, 30), 'Ps': (198, 203, 113), 'Pt': (250, 250, 160),
    'Ptm': (232, 255, 100), 'Pu': (94, 207, 145), 'Pyc': (215, 80, 145),
    'Qca': (77, 166, 211), 'Qf': (255, 176, 255), 'Qh': (212, 212, 255),
    'Qib': (0, 159, 159), 'Qii': (132, 194, 255), 'Qpe': (255, 176, 255),
    'Qpy': (87, 105, 151), 'Qr': (165, 224, 236), 'Qru': (85, 200, 200),
    'Qs': (172, 255, 255), 'RIB': (255, 255, 77), 'Rp': (232, 255, 100),
    'Sa': (255, 155, 80), 'Soa': (172, 80, 150), 'Sod': (240, 210, 0),
    'Sot': (150, 100, 50), 'Sou': (177, 134, 86), 'Tb': (255, 200, 100),
    'Tic': (255, 200, 0), 'Tip': (255, 140, 0), 'Ug': (255, 230, 130),
    'Um': (255, 230, 0), 'a': (0, 128, 255), 'c': (225, 208, 186),
    'd': (220, 220, 220), 'm': (162, 122, 122), 'p': (215, 215, 175),
    'r': (166, 166, 166), 'u': (230, 230, 230), 'v': (230, 230, 250),
}


def get_color_vegetacio(codi_for, codi_us=None):
    """
    Retorna (R, G, B) per a una tipologia forestal.
    Prioritat: codi_us (si forestal) > codi_for > gris per defecte.
    """
    # Si hi ha codi d'ús forestal, té prioritat per al color
    if codi_us and codi_us in COLORS_VEGETACIO:
        if is_forestal(codi_us):
            return COLORS_VEGETACIO[codi_us]
    # Color per la formació forestal
    if codi_for and codi_for in COLORS_VEGETACIO:
        return COLORS_VEGETACIO[codi_for]
    # Per defecte: verd clar genèric
    return (180, 230, 180)
